"""
Export the whole study as a single self-contained HTML viewer.

The viewer is generated BY the calculation engine, not written alongside it:
every number and every plotted point in the page comes from the same functions
that produce the markdown report and the matplotlib figures. There is no second
implementation of the physics in JavaScript - the browser only draws curves that
Python has already sampled.

Curves are sampled logarithmically over the plotting range and rounded to four
significant figures, which keeps the embedded payload small enough to ship
inside one HTML file while staying well inside plotting accuracy.
"""

from __future__ import annotations

import datetime as _dt
import json
import math
from pathlib import Path
from typing import Callable, Iterable

import numpy as np

from checks import derated_ampacity, recommend_cable_size
from constants import (
    CTI_S,
    DAMAGE_CURVE_MIN_MULTIPLE,
    INSTANTANEOUS_MIN_MULTIPLE,
    INSTANTANEOUS_SET_MULTIPLE,
    K_ADIABATIC_CU_XLPE,
    LOCKED_ROTOR_PICKUP_FRACTION,
    TEMP_XLPE_OPERATING_C,
    THETA_MARGINAL,
)
from models import Plant
from protection import damage_time, worst
from report import StudyResults
from starting import DELTA, STAR, critical_transformer_kva

#: Plot window, matching the matplotlib TCC sheets so the two agree.
I_MIN, I_MAX = 10.0, 1.0e5
T_MIN, T_MAX = 0.01, 1.0e4

SAMPLES = 160


def _sig(x: float, digits: int = 4) -> float:
    """Round to a fixed number of significant figures, for a compact payload."""
    if x == 0 or not math.isfinite(x):
        return 0.0
    return round(x, -int(math.floor(math.log10(abs(x)))) + (digits - 1))


def _sample(fn: Callable[[float], float], i_lo: float, i_hi: float) -> list[list[float]]:
    """Sample a trip-time function, dropping points outside the plot window."""
    pts: list[list[float]] = []
    lo, hi = max(i_lo, I_MIN), min(i_hi, I_MAX)
    if hi <= lo:
        return pts
    for i_a in np.geomspace(lo, hi, SAMPLES):
        t = fn(float(i_a))
        if math.isfinite(t) and T_MIN <= t <= T_MAX:
            pts.append([_sig(float(i_a)), _sig(t)])
    return pts


def _envelope(motor) -> list[list[float]]:
    """Starting envelope as an explicit staircase, ready to draw.

    Value at a current is the total time the motor spends at or above it while
    accelerating, so the relay curve must stay above this everywhere.
    """
    stages = sorted(motor.starting_stages(), key=lambda s: s[0])
    pts = [[I_MIN, _sig(motor.t_start_s)]]
    remaining = motor.t_start_s
    for current, duration, _ in stages:
        pts.append([_sig(current), _sig(remaining)])          # step across
        remaining = max(remaining - duration, 0.0)
        pts.append([_sig(current), _sig(max(remaining, T_MIN))])  # step down
    return pts


def _check(c) -> dict:
    return {
        "id": c.id,
        "name": c.name,
        "criterion": c.criterion,
        "value": c.value,
        "verdict": c.verdict,
        "reference": c.reference,
        "note": c.note,
    }


def _starting_case(r) -> dict:
    return {
        "vBus": _sig(r.v_bus_pu * 100, 4),
        "vMotor": _sig(r.v_motor_pu * 100, 4),
        "iStart": round(r.i_start_a),
        "iNameplate": round(r.i_nameplate_a),
        "torque": round(r.torque_pu * 100),
        "verdict": r.verdict,
    }


def build_payload(results: StudyResults, settings_mode: str = "specified") -> dict:
    """Assemble everything the viewer needs into one JSON-serialisable dict."""
    p: Plant = results.plant
    sc = results.sc
    t = p.transformer

    motors = []
    for m in p.motors:
        s = results.settings[m.tag]
        hi, lo = sc.terminal_max[m.tag], sc.terminal_min[m.tag]
        vd_v, vd_pct = results.starting.voltage_drop[m.tag]

        motors.append(
            {
                "tag": m.tag,
                "service": m.service,
                "kw": m.kw,
                "voltage": m.voltage_v,
                "efficiency": m.efficiency,
                "pf": m.pf,
                "flc": _sig(m.flc_a),
                "kva": _sig(m.s_rated_kva),
                "lrcMultiple": m.lrc_multiple,
                "ilr": round(m.i_lr_a),
                "startMethod": "star-delta" if m.is_star_delta else "DOL",
                "isStarDelta": m.is_star_delta,
                "tStart": m.t_start_s,
                "tStar": m.t_star_s,
                "tDelta": _sig(m.t_delta_s),
                "tStallHot": m.t_stall_hot_s,
                "tStallCold": m.t_stall_cold_s,
                "cable": {
                    "size": m.cable.size_mm2,
                    "runs": m.cable.runs,
                    "length": m.cable.length_m,
                    "iz": round(derated_ampacity(m.cable)),
                    "minSize": recommend_cable_size(p, m),
                    "r90": _sig(m.cable.r_ohm(TEMP_XLPE_OPERATING_C) * 1000),
                    "x": _sig(m.cable.x_ohm() * 1000),
                    "vdVolts": _sig(vd_v),
                    "vdPct": _sig(vd_pct),
                },
                "settings": {
                    "pickup": _sig(s.pickup_a),
                    "pickupMultiple": s.pickup_multiple,
                    "tripClass": s.trip_class,
                    "tau": round(s.tau_s),
                    "thetaRunning": _sig(s.theta_hot),
                    "lrPickup": round(s.lr_pickup_a),
                    "lrTime": _sig(s.lr_time_s) if s.lr_time_s else None,
                    "lrWindow": [_sig(s.lr_window_s[0]), _sig(s.lr_window_s[1])],
                    "lrDwell": _sig(s.lr_dwell_s),
                    "instPickup": round(s.inst_pickup_a),
                    "instClearing": s.inst_clearing_s,
                    "mccbFrame": s.mccb_frame_a,
                    "mccbIcu": s.mccb_icu_ka,
                    "thetaHot": _sig(s.sim_hot.theta_max),
                    "thetaCold": _sig(s.sim_cold.theta_max),
                    "tripsHot": s.sim_hot.trips,
                    "tripTime": _sig(s.sim_hot.trip_time_s) if s.sim_hot.trip_time_s else None,
                    "recommendation": s.recommendation,
                    "asSpecified": s.as_specified,
                    "specifiedClass": m.trip_class,
                    "specifiedPickup": m.ol_pickup_multiple,
                },
                "reasoning": dict(s.reasoning),
                "checks": [_check(c) for c in s.checks] + [
                    _check(c) for c in results.cable_checks[m.tag]
                ],
                # Worst verdict across everything that belongs to this motor:
                # its protection settings, its cable, and its starting case.
                "verdict": worst(
                    [s.verdict, results.starting.as_designed(p, m.tag, True).verdict]
                    + [c.verdict for c in results.cable_checks[m.tag]]
                ),
                "fault": {
                    "maxDevice": round(hi.device_ik_a),
                    "maxTotal": round(hi.total_ik_a),
                    "backfeed": round(hi.motor_ik_a),
                    "minDevice": round(lo.device_ik_a),
                },
                "starting": {
                    "dolAlone": _starting_case(results.starting.get(m.tag, DELTA, False)),
                    "dolOthers": _starting_case(results.starting.get(m.tag, DELTA, True)),
                    "starAlone": _starting_case(results.starting.get(m.tag, STAR, False)),
                    "starOthers": _starting_case(results.starting.get(m.tag, STAR, True)),
                },
                "criticalKva": round(critical_transformer_kva(p, m, DELTA, True) or 0),
                "recommendation": results.starting.recommendations[m.tag],
                "zLr": _sig(abs(m.z_lr()) * 1000),
                "curves": {
                    "device": _sample(lambda i, s=s: s.device_time(i, hot=True),
                                      s.pickup_a * 1.0005, I_MAX),
                    "thermalCold": _sample(lambda i, s=s: s.thermal_time(i, hot=False),
                                           s.pickup_a * 1.0005, I_MAX),
                    "damageHot": _sample(lambda i, m=m: damage_time(m, i, hot=True),
                                         DAMAGE_CURVE_MIN_MULTIPLE * m.flc_a, I_MAX),
                    "damageCold": _sample(lambda i, m=m: damage_time(m, i, hot=False),
                                          DAMAGE_CURVE_MIN_MULTIPLE * m.flc_a, I_MAX),
                    "envelope": _envelope(m),
                },
                "markers": [
                    {"i": round(m.flc_a), "label": "FLC"},
                    {"i": round(m.i_lr_a), "label": "LRC"},
                    {"i": round(lo.device_ik_a), "label": "Ik min"},
                    {"i": round(sc.bus_max.ik_a), "label": "Ik bus"},
                ],
                "thermalTrace": {
                    "hot": {
                        "t": [_sig(v, 3) for v in s.sim_hot.trace_t],
                        "theta": [_sig(v, 4) for v in s.sim_hot.trace_theta],
                    },
                    "cold": {
                        "t": [_sig(v, 3) for v in s.sim_cold.trace_t],
                        "theta": [_sig(v, 4) for v in s.sim_cold.trace_theta],
                    },
                },
                "stages": [
                    {
                        "label": d["label"],
                        "current": round(d["current_a"]),
                        "duration": d["duration_s"],
                        "thetaStart": _sig(d["theta_start"]),
                        "thetaEnd": _sig(d["theta_end"]),
                    }
                    for d in s.sim_hot.stage_results
                ],
            }
        )

    return {
        "meta": {
            "project": p.meta.get("project", "Motor Protection Study"),
            "bus": p.meta.get("bus_designation", "Bus"),
            "revision": p.meta.get("revision", "-"),
            "basis": p.meta.get("basis", ""),
            "generated": _dt.date.today().isoformat(),
            "scenario": p.scenario,
            "scenarioDescription": p.scenario_description,
            "settingsMode": settings_mode,
        },
        "overall": results.overall,
        "counts": results.counts(),
        "plant": {
            "source": {"faultMva": p.source.fault_mva, "xr": p.source.x_over_r},
            "transformer": {
                "kva": t.kva,
                "hv": t.hv_kv,
                "lv": t.lv_v,
                "group": t.vector_group,
                "uk": t.uk_pct,
                "loadLoss": t.load_loss_kw,
                "rPct": _sig(t.r_pct),
                "xPct": _sig(t.x_pct),
                "xr": _sig(t.x_over_r),
                "flc": _sig(t.flc_a),
                "zBase": _sig(t.z_base_ohm * 1000),
            },
            "bus": {
                "voltage": p.bus.nominal_v,
                "frequency": p.bus.frequency_hz,
                "icw": p.bus.rated_short_time_withstand_ka,
            },
            "staticLoad": {"kva": p.static_load.kva, "pf": p.static_load.pf},
            "diversity": p.motor_diversity_factor,
            "loading": {
                "connected": _sig(p.connected_kva),
                "diversified": _sig(p.diversified_kva),
                "pct": _sig(p.transformer_loading_pct),
                "pf": _sig(p.diversified_pf),
            },
            "zSource": _sig(abs(p.z_source) * 1000),
            "feeder": {
                "designation": p.feeder.designation,
                "frame": p.feeder.frame_a,
                "icu": p.feeder.icu_ka,
                "ir": p.feeder.ir_a,
                "tr": p.feeder.tr_s,
                "isd": p.feeder.isd_a,
                "tsd": p.feeder.tsd_s,
                "ii": p.feeder.ii_a,
            },
            "criteria": p.criteria,
        },
        "shortCircuit": {
            "busMax": {
                "ik": _sig(sc.bus_max.ik_ka),
                "ip": _sig(sc.bus_max.ip_ka),
                "kappa": _sig(sc.bus_max.kappa),
                "r": _sig(sc.bus_max.r * 1000),
                "x": _sig(sc.bus_max.x * 1000),
                "xr": _sig(sc.bus_max.x_over_r),
            },
            "busNetwork": {"ik": _sig(sc.bus_max_no_motors.ik_ka)},
            "busMin": {"ik": _sig(sc.bus_min.ik_ka)},
            "motorUplift": _sig(sc.motor_contribution_pct),
            "kt": _sig(sc.kt, 5),
        },
        "motors": motors,
        "feederCurve": _sample(p.feeder.trip_time_s, p.feeder.ir_a * 1.0005, I_MAX),
        "plantChecks": [_check(c) for c in results.plant_checks.checks],
        "worstStart": {
            "tag": results.plant_checks.worst_start_tag,
            "current": round(results.plant_checks.worst_start_bus_current_a),
        },
        "findings": [
            {"tag": tag, **_check(c)} for tag, c in results.findings()
        ],
        "constants": {
            "thetaMarginal": THETA_MARGINAL,
            "cti": CTI_S,
            "instMin": INSTANTANEOUS_MIN_MULTIPLE,
            "instSet": INSTANTANEOUS_SET_MULTIPLE,
            "lrFraction": LOCKED_ROTOR_PICKUP_FRACTION,
            "damageMin": DAMAGE_CURVE_MIN_MULTIPLE,
            "kAdiabatic": K_ADIABATIC_CU_XLPE,
        },
        "plot": {"iMin": I_MIN, "iMax": I_MAX, "tMin": T_MIN, "tMax": T_MAX},
    }


#: The template is authored as a body fragment so it can be published directly
#: as a hosted artifact, which supplies its own document skeleton. For the
#: local file we wrap it ourselves so it is a valid standalone document.
_SKELETON = (
    '<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
    '<meta name="viewport" content="width=device-width,initial-scale=1">\n'
    "{head}</head>\n<body>\n{body}\n</body>\n</html>\n"
)


def render_viewer(results: StudyResults, template: str | Path | None = None,
                  settings_mode: str = "specified", standalone: bool = True) -> str:
    """Return the viewer HTML with the study data embedded."""
    if template is None:
        template = Path(__file__).resolve().parent.parent / "web" / "template.html"
    html = Path(template).read_text(encoding="utf-8")

    if "__STUDY_DATA__" not in html:
        raise ValueError("viewer template is missing the __STUDY_DATA__ placeholder")
    payload = json.dumps(build_payload(results, settings_mode), separators=(",", ":"))
    html = html.replace("__STUDY_DATA__", payload)

    if not standalone:
        return html

    # Lift <title> and <link rel=stylesheet> into a real <head>.
    head_lines, body_lines = [], []
    for line in html.split("\n"):
        stripped = line.strip()
        if stripped.startswith("<title>") or stripped.startswith("<link "):
            head_lines.append(line)
        else:
            body_lines.append(line)
    return _SKELETON.format(head="\n".join(head_lines) + "\n", body="\n".join(body_lines))


def write_viewer(
    results: StudyResults,
    outdir: str | Path,
    template: str | Path | None = None,
    settings_mode: str = "specified",
) -> Path:
    """Render the standalone interactive viewer to <outdir>/index.html."""
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    path = outdir / "index.html"
    path.write_text(
        render_viewer(results, template, settings_mode, standalone=True), encoding="utf-8"
    )
    return path
